# Generated by Django 3.1 on 2020-09-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cus_id',
        ),
        migrations.AddField(
            model_name='products',
            name='cus_id',
            field=models.ManyToManyField(to='inventory.Customer'),
        ),
    ]
